select * from DIM_TEMPO

CREATE OR ALTER PROCEDURE SP_DIM_TEMPO_INSERT (@DATA_INICIAL DATETIME, @DATA_FINAL DATETIME)
AS
BEGIN
	SET LANGUAGE BRAZILIAN

	DECLARE @DIA INT,
			@MES INT, @MES_A INT,
			@YEAR INT, @YEAR_A INT,
			@FDS VARCHAR(3)

	SET @DIA = DAY(@DATA_INICIAL)
	SET @MES = MONTH(@DATA_INICIAL)
	SET @YEAR = YEAR(@DATA_INICIAL)
	SET @MES_A = @MES
	SET @YEAR_A = @YEAR


	WHILE(@DATA_INICIAL <= @DATA_FINAL)
	BEGIN
		WHILE(@YEAR = YEAR(@DATA_INICIAL))
		BEGIN
			WHILE(@MES = MONTH(@DATA_INICIAL))
			BEGIN
				--VERIFICA FINL DE SEMANA
				SET @FDS = IIF(DATENAME(DW, @DATA_INICIAL) IN ('Sábado', 'Domingo'), 'SIM', 'NAO')

				--INSERÇÃO
				INSERT INTO DIM_TEMPO VALUES(
					'DIA',
					@DATA_INICIAL,
					@DIA,
					DATENAME(DD, @DATA_INICIAL),
					@FDS,
					@MES,
					DATENAME(MM, @DATA_INICIAL),
					DATEPART(QQ,@DATA_INICIAL),
					TRIM(STR(DATENAME(QQ, @DATA_INICIAL)) + '° Trimestre'),
					IIF(@MES<7, 1,2),
					IIF(@MES<7, '1° Semestre', '2° Semestre'),
					@YEAR
				)
				--INCREMENTA A DATA PARA O PROXIMO DIA
				SET @DATA_INICIAL = DATEADD(DD, 1, @DATA_INICIAL)
			END
			--INSERIR O MES, MAS AQUI TEMOS Q DIMINUIR UMA DATA PRA PODER PEGAR O MES ANTERIOR
			INSERT INTO DIM_TEMPO VALUES(
					'MES',
					NULL,
					NULL,
					NULL,
					NULL,
					@MES,
					DATENAME(MM, DATEADD(DD, -1,@DATA_INICIAL)),
					DATEPART(QQ,DATEADD(DD, -1,@DATA_INICIAL)),
					TRIM(STR(DATENAME(QQ, DATEADD(DD, -1,@DATA_INICIAL))) + '° Trimestre'),
					IIF(@MES<7, 1,2),
					IIF(@MES<7, '1° Semestre', '2° Semestre'),
					@YEAR
				)
			--INCREMENTAMOS A DATA NOVAMENTE E ATRIBUIMOS O NOVO MES
			SET @MES_A = @MES
			SET @MES = MONTH(@DATA_INICIAL)
		END
		--INSERTA O ANO
		INSERT INTO DIM_TEMPO VALUES(
					'ANO',
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					NULL,
					@YEAR
		)
		SET @YEAR_A = @YEAR
		SET @YEAR = YEAR(@DATA_INICIAL)
	END
END

DELETE FROM DIM_TEMPO
SELECT * FROM DIM_TEMPO

EXEC SP_DIM_TEMPO_INSERT '20210101', '20221230'
