USE BD_REDE_POSTOS

CREATE OR ALTER PROCEDURE SP_OLTP_LOJA(@DATA DATETIME)
AS
BEGIN
	INSERT INTO TB_AUX_LOJA
	SELECT @DATA, L.COD_LOJA, L.NM_LOJA, F.NM_FUNCIONARIO, C.CIDADE, E.ESTADO, E.SIGLA
	FROM TB_LOJA L INNER JOIN TB_FUNCIONARIO F
	ON (L.COD_GERENTE = F.COD_FUNCIONARIO) INNER JOIN TB_CIDADE C
	ON (L.COD_CIDADE = C.COD_CIDADE) INNER JOIN TB_ESTADO E
	ON (C.COD_ESTADO = E.COD_ESTADO)
END

EXEC SP_OLTP_LOJA '20220929'