USE BD_REDE_POSTOS

CREATE OR ALTER PROCEDURE SP_OLTP_PRODUTO (@DATA DATETIME)
AS 
BEGIN
	INSERT INTO TB_AUX_PRODUTO
	SELECT @DATA, P.COD_PRODUTO, P.PRODUTO, SC.COD_SUBCATEGORIA, SC.SUBCATEGORIA, C.COD_CATEGORIA, C.CATEGORIA
	FROM TB_PRODUTO P JOIN TB_SUBCATEGORIA SC
	ON (P.COD_SUBCATEGORIA = SC.COD_SUBCATEGORIA) JOIN TB_CATEGORIA C
	ON (SC.COD_CATEGORIA = C.COD_CATEGORIA)
END

SELECT * FROM TB_AUX_PRODUTO

EXEC SP_OLTP_PRODUTO '20220929'