CREATE DATABASE TRIGGER03

USE TRIGGER03

--1. Criar uma tabela TB_FUNCIONARIO com os seguintes atributos: MATRICULA, NOME, SALARIO,
--GRATIFICACAO. A Matricula representa a chave primária. Os atributosSALARIO e GRATIFICACAO
--poderão assumir valores NULOS (NULL).
CREATE TABLE TB_FUNCIONARIO(
	MATRICULA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,
	SALARIO NUMERIC (10,2),
	GRATIFICACAO NUMERIC(10,2)
)

--2. Criar uma tabela de auditoria TB_LOG_AUMENTO_FUNCIONARIO comos seguintesatributos: MATRICULA,
--NOME, DATA, SALARIO_INTEGRAL_ANTIGO, SALARIO_INTEGRAL_NOVO. Essa tabela será utilizada para registrar
--os aumentos de salários que ocorrerem na tabela TB_FUNCIONARIO. Serão registradas as mudanças em que
--a soma Salário novo + Gratificação nova é maior que Salário antigo+Gratificação antiga.
CREATE TABLE TB_LOG_AUMENTO_FUNCIONARIO(
	MATRICULA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,
	DATA DATETIME,
	SALARIO_INTEGRAL_ANTIGO NUMERIC (10,2),
	SALARIO_INTEGRAL_NOVO NUMERIC (10,2)
)

--3. Criar uma Trigger na tabela TB_FUNCIONARIO capaz de registrar os aumentos de salário integral (salário + gratificação).
CREATE OR ALTER TRIGGER TG_LOG_FUNC_UPDATE
ON TB_FUNCIONARIO
AFTER UPDATE
AS
BEGIN
	DECLARE @SALARIO NUMERIC(10,2),
			@GRATIFICACAO NUMERIC(10,2),
			@MATRICULA INT, @NOME VARCHAR(30),
			@S_ATUAL NUMERIC(10,2), @S_ANT NUMERIC(10,2)

	DECLARE C_FUN CURSOR FOR SELECT MATRICULA, NOME, SALARIO, GRATIFICACAO FROM TB_FUNCIONARIO
	OPEN C_FUN
	FETCH C_FUN INTO @MATRICULA, @NOME, @SALARIO, @GRATIFICACAO

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		SET @S_ATUAL = @SALARIO + @GRATIFICACAO
		SET @S_ANT = (SELECT SALARIO + GRATIFICACAO FROM DELETED D WHERE D.MATRICULA = @MATRICULA)

		IF(@S_ATUAL > @S_ANT)
			INSERT INTO TB_LOG_AUMENTO_FUNCIONARIO VALUES (@MATRICULA, @NOME, GETDATE(), @S_ANT, @S_ATUAL)

		FETCH C_FUN INTO @MATRICULA, @NOME, @SALARIO, @GRATIFICACAO
	END
	CLOSE C_FUN
	DEALLOCATE C_FUN
END

INSERT INTO TB_FUNCIONARIO VALUES (1, 'JOAO', 1100, 500)
INSERT INTO TB_FUNCIONARIO VALUES (2, 'MARIA', 1600, 300)

UPDATE TB_FUNCIONARIO
SET SALARIO = 1000, GRATIFICACAO = 700
WHERE MATRICULA = 1

SELECT * FROM TB_FUNCIONARIO
SELECT * FROM TB_LOG_AUMENTO_FUNCIONARIO

DELETE FROM TB_FUNCIONARIO

