CREATE DATABASE TRIGGER05

USE TRIGGER05

CREATE TABLE TB_VENDAS (
   CD_VENDA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   DT_VENDA DATETIME NOT NULL,
   CD_PRODUTO INT NOT NULL,
   QUANTIDADE INT NOT NULL,
   VALOR NUMERIC(10,2) NOT NULL
)


/* Tabela para log de alterações na tabela de Vendas. As alterações podem
   ser de três tipos: (I - Inclusao, A - Alteracao, R - Remocao). O Log
   sempre armazena os valores antigos e os novos valores. Somente os 
   os atributos QUANTIDADE e VALOR podem ser alterados para uma venda. */

CREATE TABLE TB_LOG_VENDAS (
    CD_LOG 		INT IDENTITY (1,1) NOT NULL,
    DT_LOG 		DATETIME NOT NULL,     -- Data em que o log foi registrado
    TIPO_OPERACAO 	CHAR(1) CHECK (TIPO_OPERACAO IN ('I','A','R')),	
    CD_VENDA 		INT NULL,
    CD_PRODUTO 		INT NULL,
    DT_VENDA 		DATETIME NULL,
    QUANTIDADE_ANTIGA   INT NULL,
    VALOR_ANTIGO	NUMERIC(10,2) NULL,
    QUANTIDADE_NOVA	INT NULL,
    VALOR_NOVO		NUMERIC(10,2) NULL 
)

CREATE OR ALTER TRIGGER TG_VENDAS_INSERT
ON TB_VENDAS
AFTER INSERT
AS
BEGIN
	INSERT INTO TB_LOG_VENDAS 
	SELECT GETDATE(), 'I', CD_VENDA, CD_PRODUTO, DT_VENDA, NULL, NULL, QUANTIDADE,VALOR
	FROM INSERTED
END

CREATE OR ALTER TRIGGER TG_VENDAS_DELETE
ON TB_VENDAS
AFTER DELETE
AS
BEGIN
	INSERT INTO TB_LOG_VENDAS 
	SELECT GETDATE(), 'R', CD_VENDA, CD_PRODUTO, DT_VENDA, QUANTIDADE, VALOR, NULL,NULL
	FROM DELETED
END

CREATE OR ALTER TRIGGER TG_VENDAS_UPDATE
ON TB_VENDAS
AFTER UPDATE
AS
BEGIN
	INSERT INTO TB_LOG_VENDAS 
	SELECT GETDATE(), 'A', I.CD_VENDA, I.CD_PRODUTO, D.DT_VENDA, D.QUANTIDADE, D.VALOR, I.QUANTIDADE,I.VALOR
	FROM DELETED D
	JOIN INSERTED I
	ON D.CD_PRODUTO = I.CD_PRODUTO
END


INSERT INTO TB_VENDAS VALUES(GETDATE(), 55, 100, 1100.00),
							(GETDATE(), 64, 1500, 300.00)

UPDATE TB_VENDAS
SET QUANTIDADE = 1000
WHERE CD_PRODUTO = 64

SELECT * FROM TB_VENDAS
SELECT * FROM TB_LOG_VENDAS

DELETE FROM TB_VENDAS WHERE CD_PRODUTO = 55

DELETE FROM TB_VENDAS
DELETE FROM TB_LOG_VENDAS
