USE PROJETO_SAD

--INSERÇÃO NAS TABELAS SEM FOREIGN KEY
INSERT INTO TB_STATUS (ID_STATUS, STATUS) VALUES 
(1, 'Em Aberto'),
(2, 'Resolvido')

INSERT INTO TB_CATEGORIA (ID_CATEGORIA, CATEGORIA) VALUES
(1, 'Manutenção de Equipamento'),
(2, 'Instalação de Equipamento'),
(3, 'Problemas com Equipamento'),
(4, 'Problemas com Software'),
(5, 'Instalação de Software'),
(6, 'Problemas na Rede')

INSERT INTO TB_ENDERECO (ID_ENDERECO, UF, CIDADE, CEP, BAIRRO, RUA, NUMERO) VALUES
(1, 'SE', 'São Cirstovão', '49100-000', 'Rosa Elze', 'Av. Marechal Rondon', null),
(2, 'SE', 'Itabaiana', '49506-036', 'Sítio Porto', 'Av. Vereador Olímpio Grande', null),
(3, 'SE', 'Lagarto', '49400-000', 'Centro', 'Av. Governador Marcelo Déda', 13)

--=======================================================================================================================================================================--

--INSERÇÃO NAS TABLEAS COM FOREIGN KEY
INSERT INTO TB_FUNCIONARIO (ID_FUNCIONARIO, MATRICULA, NOME, TELEFONE, EMAIL, DATA_INICIO_CONTRATO, DATA_FIM_CONTRATO, ID_DEPARTAMENTO, ID_ORGAO_RESPONSAVEL) VALUES
(1, '200600000001', 'Jovinianour Valter de Santana Son', '11111111111111', 'diretor.sc@uf.br',  '01/01/2006', null, null, null),
(2, '200600000002', 'Hugo Vitu Sarmen Vilturinior',      '22222222222222', 'diretor.ita@uf.br', '01/01/2006', null, null, null)

INSERT INTO TB_CAMPUS (ID_CAMPUS, CNPJ, NOME, TELEFONE, ID_ENDERECO, ID_DIRETOR) VALUES
(1, '67.787.686/0001-83', 'Cidade Univ. Prof. José Aloísio de Campos', '+55 79 3996-6699', 1, 1),
(2, '07.660.586/0001-60', 'Campus Prof. Alberto Carvalho', '+55 79 3822-8288', 2, 2)

												------------------------------------------------------------------

INSERT INTO TB_DEPARTAMENTO (ID_DEPARTAMENTO, COD_DEPARTAMENTO, NOME, SIGLA, DESCRICAO, ID_DIRETOR, ID_CAMPUS) VALUES
--CAMPUS ALBERTO
(1, 1, 'DEPARTAMENTO DE EDUCAÇÃO', 'DEDI', ' ', null, 2),
(2, 2, 'DDEPARTAMENTO DE SISTEMA DE INFORMAÇÃO', 'DSI', ' ', null, 2),
--CAMPUS JOSE
(3, 1, 'DEPARTAMENTO DE COMPUTAÇÃO', 'DECOMP', ' ', null, 1),
(4, 2, 'DEPARTAMENTO DE FÍSICA', 'DFI', ' ', null, 1 )

INSERT INTO TB_ORGAO_RESPONSAVEL (ID_ORGAO_RESPONSAVEL, COD_ORGAO_RESPONSAVEL, NOME, SIGLA, ID_COORDENADOR, ID_CAMPUS) VALUES
(2, 1, 'Centro de Processamento de Dados', 'CPD', null, 2),
(1, 1, 'Superintendência de Tecnologia da Informação', 'STI', null, 1)

INSERT INTO TB_FUNCIONARIO (ID_FUNCIONARIO, MATRICULA, NOME, TELEFONE, EMAIL, DATA_INICIO_CONTRATO, DATA_FIM_CONTRATO, ID_DEPARTAMENTO, ID_ORGAO_RESPONSAVEL) VALUES
(3, '200600000003', 'Elsa de Arendelle', '333333333333', 'diretor.dedi@uf.br', '01/01/2006', null, 1, null),
(4, '200600000004', 'Bruce Wayne', '444444444444', 'diretor.dsi@uf.br',  '01/01/2006', null, 2, null),
(5, '200600000005', 'Clark Kent Kal-El', '555555555555', 'diretor.decomp@uf.br', '01/01/2006', null, 3, null),
(6, '200600000006', 'Diana Prince', '666666666666', 'diretor.dfi@uf.br', '01/01/2006', null, 4, null),
(7, '200600000007', 'Marcus Túlio de Araújo Machado', '777777777777', 'coordenador.cpd@uf.br', '01/01/2006', null, null, 2),
(8, '200600000008', 'Andrés Ignácio Martinez Menéndez', '888888888888', '', '01/01/2006', null, null, 1)

--UPDATE DEPARTAMENTO
UPDATE TB_DEPARTAMENTO
SET ID_DIRETOR = 3
WHERE ID_DEPARTAMENTO = 1

UPDATE TB_DEPARTAMENTO
SET ID_DIRETOR = 4
WHERE ID_DEPARTAMENTO = 2

UPDATE TB_DEPARTAMENTO
SET ID_DIRETOR = 5
WHERE ID_DEPARTAMENTO = 3

UPDATE TB_DEPARTAMENTO
SET ID_DIRETOR = 6
WHERE ID_DEPARTAMENTO = 4

--UPDATE ORGAO
UPDATE TB_ORGAO_RESPONSAVEL
SET ID_COORDENADOR = 7
WHERE ID_ORGAO_RESPONSAVEL = 2

UPDATE TB_ORGAO_RESPONSAVEL
SET ID_COORDENADOR = 8
WHERE ID_ORGAO_RESPONSAVEL = 1

--=======================================================================================================================================================================--
/* TESTES

SELECT * FROM TB_CAMPUS
SELECT * FROM TB_CATEGORIA
SELECT * FROM TB_DEPARTAMENTO
SELECT * FROM TB_ENDERECO
SELECT * FROM TB_FUNCIONARIO
SELECT * FROM TB_ORGAO_RESPONSAVEL
SELECT * FROM TB_STATUS


--SELECT PARA CADA DEPARTAMENTO, SEUS DIRETORES, CAMPUS A QUAL PERTECEM, E DIRETORES/RETIORES DO CAMPUS
SELECT D.NOME,  F.NOME AS 'DIRETOR_DEPARTAMENTO', C.NOME AS 'CAMPUS', F2.NOME AS 'DIRETOR_CAMPUS'
FROM TB_DEPARTAMENTO D JOIN TB_CAMPUS C
ON (D.ID_CAMPUS = C.ID_CAMPUS)
JOIN TB_FUNCIONARIO F
ON (D.ID_DIRETOR = F.ID_FUNCIONARIO) 
JOIN TB_FUNCIONARIO F2
ON(C.ID_DIRETOR = F2.ID_FUNCIONARIO)

--SELECT PARA CADA ORGAO RESPONSAVEL, SEUS COORDENADORES, CAMPUS A QUAL PERTECEM, E DIRETORES/RETIORES DO CAMPUS
SELECT D.SIGLA AS 'ORGAO',  F.NOME AS 'DIRETOR_DEPARTAMENTO', C.NOME AS 'CAMPUS', F2.NOME AS 'DIRETOR_CAMPUS'
FROM TB_ORGAO_RESPONSAVEL D JOIN TB_CAMPUS C
ON (D.ID_CAMPUS = C.ID_CAMPUS)
JOIN TB_FUNCIONARIO F
ON (D.ID_COORDENADOR = F.ID_FUNCIONARIO) 
JOIN TB_FUNCIONARIO F2
ON(C.ID_DIRETOR = F2.ID_FUNCIONARIO)

--CAMPUS E ENDEREÇOS
SELECT C.NOME AS 'CAMPUS', E.CIDADE, E.RUA, ISNULL(E.NUMERO, 0) AS 'NUMERO', C.TELEFONE
FROM TB_CAMPUS C JOIN
TB_ENDERECO E
ON (C.ID_ENDERECO = E.ID_ENDERECO)

*/
