CREATE OR ALTER FUNCTION SF_TO_DATE(@DATA VARCHAR(20), @FORMATO VARCHAR(20))
RETURNS DATETIME AS
BEGIN
	DECLARE @DATA_FORMATADA DATETIME

	DECLARE @SS_INDEX INT, @MI_INDEX INT, @HH_INDEX INT, @DD_INDEX INT, @MM__INDEX INT, @YYYY_INDEX INT 

	SET @SS_INDEX = CHARINDEX('SS',@DATA) 
	SET @MI_INDEX =
	SET @HH_INDEX =
	SET @DD_INDEX =
	SET @MM_INDEX =
	SET @MM_INDEX =
	SET @YYYY_INDEX =


	SET @DATA = REPLACE(@MASK,'DD',DAY(@DATA))
	SET @DATA = REPLACE(@MASK,'MM',MONTH(@DATA))
	SET @DATA = REPLACE(@MASK,'YYYY',YEAR(@DATA))
	SET @DATA = REPLACE(@MASK,'HH', DATEPART(HH, @DATA))
	SET @DATA = REPLACE(@MASK,'MI', DATEPART(MI, @DATA))
	SET @DATA = REPLACE(@MASK,'SS', DATEPART(SS, @DATA))
	SET @DATA = REPLACE(@MASK,'Month',DATENAME(MONTH, @DATA))


	RETURN @DATA_FORMATADA
END