-- Scripts ddl para o ambiente dimensional

USE bd_rede_postos

DROP TABLE IF EXISTS FATO_VENDA
DROP TABLE IF EXISTS DIM_PRODUTO
DROP TABLE IF EXISTS DIM_LOJA
DROP TABLE IF EXISTS DIM_FUNCIONARIO
DROP TABLE IF EXISTS DIM_TEMPO
DROP TABLE IF EXISTS DIM_TIPO_PAGAMENTO


CREATE TABLE DIM_PRODUTO (
   ID_PRODUTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   COD_PRODUTO INT NOT NULL,
   PRODUTO VARCHAR(100) NOT NULL,
   COD_SUBCATEGORIA INT NOT NULL,
   SUBCATEGORIA VARCHAR(100) NOT NULL,
   COD_CATEGORIA INT NOT NULL,
   CATEGORIA VARCHAR(100) NOT NULL
)

-- Apenas por questão didática. O número de linhas da dimensão
-- não justica a criação de índices.
CREATE INDEX IX_DIM_PRODUTO_COD_PRODUTO ON DIM_PRODUTO(COD_PRODUTO)

CREATE TABLE DIM_LOJA (
	ID_LOJA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD_LOJA INT NOT NULL,
	LOJA VARCHAR(100) NOT NULL,
	GERENTE VARCHAR(100) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	ESTADO VARCHAR(100) NOT NULL,
	SIGLA_ESTADO VARCHAR(2) NOT NULL,
	DT_INICIO DATETIME NOT NULL,
	DT_FIM DATETIME NULL,
	FL_CORRENTE VARCHAR(3) NOT NULL CHECK(FL_CORRENTE IN ('SIM','NAO'))
)


CREATE INDEX IX_DIM_LOJA_COD_LOJA ON DIM_LOJA(COD_LOJA, FL_CORRENTE)


CREATE TABLE DIM_FUNCIONARIO (
    ID_FUNCIONARIO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD_FUNCIONARIO INT NOT NULL,
	FUNCIONARIO VARCHAR(100) NOT NULL,
	COD_CARGO INT NOT NULL,
	CARGO VARCHAR(100) NOT NULL
)


CREATE INDEX IX_DIM_FUNCIONARIO_COD_FUNCIONARIO ON DIM_FUNCIONARIO(COD_FUNCIONARIO)

CREATE TABLE DIM_TIPO_PAGAMENTO (
	ID_TIPO_PAGAMENTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	COD_TIPO_PAGAMENTO INT NOT NULL,
	TIPO_PAGAMENTO VARCHAR(100)
)


CREATE INDEX IX_DIM_TIPO_PAGAMENTO_COD_TIPO_PAGAMENTO 
ON DIM_TIPO_PAGAMENTO(COD_TIPO_PAGAMENTO)


CREATE TABLE DIM_TEMPO (
	ID_TEMPO BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NIVEL VARCHAR(8) NOT NULL CHECK (NIVEL IN ('DIA','MES','ANO')),
	DATA DATETIME NULL,
	DIA INT  NULL,
	DIA_SEMANA VARCHAR(50)  NULL,
	FIM_SEMANA VARCHAR(3)  NULL CHECK (FIM_SEMANA IN ('SIM','NAO')),
	MES INT  NULL,
	NOME_MES VARCHAR(100)  NULL,
	TRIMESTRE INT  NULL,
	NOME_TRIMESTRE VARCHAR(100)  NULL,
	SEMESTRE INT  NULL,
	NOME_SEMESTRE VARCHAR(100)  NULL,
	ANO INT NOT NULL
)

CREATE INDEX IX_DIM_TEMPO_DATA ON DIM_TEMPO (DATA)
CREATE INDEX IX_DIM_TEMPO_DATA_MES ON DIM_TEMPO (NIVEL, MES)
CREATE INDEX IX_DIM_TEMPO_DATA_ANO ON DIM_TEMPO (NIVEL, ANO)

CREATE TABLE FATO_VENDA (
	ID_VENDA BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_TEMPO BIGINT NOT NULL,
	ID_LOJA INT NOT NULL,
	ID_FUNCIONARIO INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_TIPO_PAGAMENTO INT NOT NULL,
	COD_VENDA BIGINT NOT NULL,
	VOLUME NUMERIC(10,2) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL DEFAULT (1)
	CONSTRAINT FK_DIM_LOJA FOREIGN KEY (ID_LOJA) REFERENCES DIM_LOJA (ID_LOJA),
	CONSTRAINT FK_DIM_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES DIM_FUNCIONARIO(ID_FUNCIONARIO),
	CONSTRAINT FK_DIM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES DIM_PRODUTO (ID_PRODUTO),
	CONSTRAINT FK_DIM_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO (ID_TEMPO),
	CONSTRAINT FK_DIM_TIPO_PAGAMENTO FOREIGN KEY (ID_TIPO_PAGAMENTO) REFERENCES DIM_TIPO_PAGAMENTO (ID_TIPO_PAGAMENTO)
)


CREATE INDEX IX_FATO_VENDA_TEMPO ON FATO_VENDA(ID_TEMPO)
CREATE INDEX IX_FATO_VENDA_PRODUTO ON FATO_VENDA(ID_PRODUTO)
CREATE INDEX IX_FATO_VENDA_LOJA ON FATO_VENDA(ID_LOJA)
CREATE INDEX IX_FATO_VENDA_FUNCIONARIO ON FATO_VENDA(ID_FUNCIONARIO)
CREATE INDEX IX_FATO_VENDA_TIPO_PAGAMENTO ON FATO_VENDA(ID_TIPO_PAGAMENTO)
CREATE INDEX IX_FATO_VENDA_COD_VENDA ON FATO_VENDA(COD_VENDA)


