-- Scripts ddl para a área de staging

USE bd_rede_postos

DROP TABLE IF EXISTS TB_AUX_PRODUTO
DROP TABLE IF EXISTS TB_AUX_LOJA
DROP TABLE IF EXISTS TB_AUX_FUNCIONARIO
DROP TABLE IF EXISTS TB_AUX_VENDA
DROP TABLE IF EXISTS TB_AUX_TIPO_PAGAMENTO


CREATE TABLE TB_AUX_PRODUTO (
   DATA_CARGA DATETIME NOT NULL,
   COD_PRODUTO INT NULL,
   PRODUTO VARCHAR(100) NULL,
   COD_SUBCATEGORIA INT NULL,
   SUBCATEGORIA VARCHAR(100) NULL,
   COD_CATEGORIA INT  NULL,
   CATEGORIA VARCHAR(100) NULL
)

CREATE TABLE TB_AUX_LOJA (
	DATA_CARGA DATETIME NOT NULL,
	COD_LOJA INT NULL,
	LOJA VARCHAR(100) NULL,
	GERENTE VARCHAR(100) NULL,
	CIDADE VARCHAR(100) NULL,
	ESTADO VARCHAR(100) NULL,
	SIGLA_ESTADO VARCHAR(2) NULL
)

CREATE TABLE TB_AUX_FUNCIONARIO (
    DATA_CARGA DATETIME NOT NULL,
	COD_FUNCIONARIO INT NULL,
	FUNCIONARIO VARCHAR(100) NULL,
	COD_CARGO INT NULL,
	CARGO VARCHAR(100) NULL
)

CREATE TABLE TB_AUX_VENDA (
	DATA_CARGA DATETIME NOT NULL,
	DATA_VENDA DATETIME NULL,
	COD_LOJA INT NULL,
	COD_FUNCIONARIO INT NULL,
	COD_PRODUTO INT  NULL,
	COD_TIPO_PAGAMENTO INT NULL,
	VOLUME NUMERIC(10,2) NULL,
	VALOR NUMERIC(10,2) NULL,
)

CREATE TABLE TB_AUX_TIPO_PAGAMENTO (
	DATA_CARGA DATETIME NOT NULL,
	COD_TIPO_PAGAMENTO INT  NULL,
	TIPO_PAGAMENTO VARCHAR(100) NULL
)